mode: hardware
jobs: 1
physicalCores: 23
rnti: 1
rank: 4
cqi: 15
encQ: 4
decQ: 4
max_mcs: 28
coreDis: dis
ru: real
vf0: 0000:11:00
vf1: 0000:11.01
mhz: 100
totalPages: 64
freeMem: 96
dl_prbs: 270
ul_prbs: 270
iter: 2
dl_queues: 80
ul_queues: 48
